apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: q871t7sue-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: q871t7sue-python 
  name: q871t7sue-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: q871t7sue-python 
